version: '3.8'

services:
  115docker:
    image: ghcr.io/dream10201/115docker:latest
    container_name: 115docker
    restart: unless-stopped
    network_mode: host
    security_opt:
      - seccomp:unconfined
    shm_size: 1gb
    user: "0:0"
    environment:
      PUID: 0
      PGID: 0
      PASSWORD: "123456"
      DISPLAY_WIDTH: "1920"
      DISPLAY_HEIGHT: "1080"
      COOKIE_CID: "xxxxxxxxx"
      COOKIE_SEID: "xxxxxxxx"
      COOKIE_UID: "xxxxxxxxx"
      COOKIE_KID: "xxxxxxxxx"
      TZ: "Asia/Shanghai"
      LC_ALL: "zh_CN.UTF-8"
    volumes:
      - /path/to/download:/opt/Downloads
